//! Loads `ml_bridge/model.onnx` from the workspace root (generated by `ml_bridge/export_dummy_onnx.py`).

use std::path::PathBuf;

use engine_core::VoteSide;
use strategies_predict::{OnnxPredictor, PredictStrategyConfig};
use strategy_api::{Bar, MarketSnapshot, OrderBookTop};

fn ml_paths() -> (PathBuf, PathBuf) {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace")
        .to_path_buf();
    (
        root.join("ml_bridge/model.onnx"),
        root.join("ml_bridge/feature_schema.json"),
    )
}

#[test]
fn dummy_onnx_mean_projection() {
    let (model, schema) = ml_paths();
    if !model.exists() {
        eprintln!(
            "skip: run ml_bridge/export_dummy_onnx.py to create {}",
            model.display()
        );
        return;
    }
    let cfg = PredictStrategyConfig {
        model_path: model,
        schema_path: schema,
        input_name: "input".into(),
        output_name: "output".into(),
        three_class: false,
    };
    let p = OnnxPredictor::from_files(&cfg).expect("load onnx");
    let snap = MarketSnapshot {
        symbol: "TEST".into(),
        book: OrderBookTop {
            best_bid: Some(100.0),
            best_ask: Some(101.0),
            bid_qty: Some(1.0),
            ask_qty: Some(1.0),
        },
        bars: vec![
            Bar {
                open: 1.0,
                high: 1.0,
                low: 1.0,
                close: 2.0,
                volume: 1.0,
            },
            Bar {
                open: 2.0,
                high: 2.0,
                low: 2.0,
                close: 3.0,
                volume: 1.0,
            },
        ],
        now_ms: 0,
    };
    let v = p.predict_vote(&snap, false).expect("vote");
    assert!(matches!(
        v.side,
        VoteSide::Buy | VoteSide::Sell | VoteSide::Hold
    ));
}
